### ISSUE TITLE
I can't find the plugin in PowerToys after installing plugin

### ISSUE THREAD

**Issue by XiangyangYzy** [hlaueriksson/Community.PowerToys.Run.Plugins#1]
I try to copy "Community.PowerToys.Run.Plugin.Bang" to "Local\AppData\Microsoft\PowerToys\PowerToys Run\Plugins" and restart PowerToys, but not find the plugin in the PowerToys Run
![image](https://github.com/hlaueriksson/Community.PowerToys.Run.Plugins/assets/99459113/2e52caff-f645-4ccf-863a-caf96c358f0a)
![image](https://github.com/hlaueriksson/Community.PowerToys.Run.Plugins/assets/99459113/bd5e8801-7161-4721-966b-f3e15876f58c)

**Comment by hlaueriksson** [comment]
I have not yet released the plugins.

If you want to install them, you can try running `deploy.ps1` in a PowerShell terminal as administrator.

My `Bang` folder in `%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Plugins` looks like this:
![image](https://github.com/hlaueriksson/Community.PowerToys.Run.Plugins/assets/1299786/59b07009-3873-480c-9166-7eda3b2a19f4)

**Comment by XiangyangYzy** [comment]
Not sure why this PowerShell script won't work.
![image](https://github.com/hlaueriksson/Community.PowerToys.Run.Plugins/assets/99459113/4268e3f9-b260-408a-8761-1fdde023d3f3)
what I’ve done wrong and maybe tell me how to fix it?  Thanks for help

**Comment by XiangyangYzy** [comment]
> I have not yet released the plugins.
> 
> If you want to install them, you can try running in a PowerShell terminal as administrator.`deploy.ps1`
> 
> My folder in looks like this:`Bang``%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Plugins` ![image](https://private-user-images.githubusercontent.com/1299786/308167207-59b07009-3873-480c-9166-7eda3b2a19f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODM2NDAsIm5iZiI6MTcwOTA4MzM0MCwicGF0aCI6Ii8xMjk5Nzg2LzMwODE2NzIwNy01OWIwNzAwOS0zODczLTQ4MGMtOTE2Ni03ZWRhM2IyYTE5ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDEyMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTllYjllN2I0MzRjMmE4NzI2Njk4NmIxMzk0NzI2YjgzZTc5YmU4MDFhYjJhMWQ3ZjQ2ZWQ3NGFjNGUxMjVmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R4-OAa6JZa_mujFJ6SSuhDXxVdtyDw0pXYad2N2pDMM)

Not sure why this PowerShell script won't work.
![image](https://github.com/hlaueriksson/Community.PowerToys.Run.Plugins/assets/99459113/cfa0d285-d3c3-42c8-b27b-3838a0ef9b7f)
what I’ve done wrong and maybe tell me how to fix it? Thanks for help

**Comment by hlaueriksson** [comment]
I'm planning to release these plugins when PowerToys `v0.79.0` drops. It shouldn't be too long.

But if you want to build them from source:
1. Install .NET 8
2. Clone or download the repo to your filesystem, for example to `C:\git\`
3. Run `deploy.ps1` in a PowerShell terminal as administrator
   - This builds and copies the plugins to `%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Plugins`
   - The script also tries to restart PowerToys

The `%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Plugins` folder should now contain these subfolders:

- `Bang`
- `DenCode`
- `Dice`
- `Need`
- `Twitch`

The important files in the subfolders are:

- `*.dll`
- `plugin.json`

**Comment by hlaueriksson** [comment]
@XiangyangYzy `Bang` and the other plugins are now released:

- https://github.com/hlaueriksson/Community.PowerToys.Run.Plugins/releases/tag/v0.79.0
